name: Build

on: [push]

jobs:
    build-linux-sdl2:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2
            - name: "apt update"
              run: sudo apt update
            - name: "Install dependencies"
              run: sudo apt install -y libsdl2-dev ninja-build
            - name: "cmake configure"
              run: cmake -S . -B build -G "Ninja" -DACTIVE_PLATFORM=SDL2
            - name: "cmake build"
              run: cmake --build build --config Release

    build-windows-sdl2:
        runs-on: windows-2025
        steps:
            - uses: actions/checkout@v2
            - name: "Download sdl2"
              run: Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.32.10/SDL2-devel-2.32.10-VC.zip" -OutFile ".\sdl2.zip"
            - name: "Extract sdl2"
              run: Expand-Archive -Path ".\sdl2.zip" -DestinationPath ".\libs\SDL2" -Force
            - name: "cmake configure"
              run: cmake -S . -B build -G "Visual Studio 17 2022" -DACTIVE_PLATFORM=SDL2
            - name: "cmake build"
              run: cmake --build build --config Release
