name: Build

on: [push]

jobs:
    build-linux-sdl2:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2
            - name: "Install dependencies"
              run: sudo apt install -y libsdl2-dev ninja-build
            - name: "cmake configure"
              run: cmake -S . -B build -G "Ninja" -DACTIVE_PLATFORM=SDL2
            - name: "cmake build"
              run: cmake --build build --config Release
